### ISSUE TITLE
Build for 10.26.0

### ISSUE THREAD

**Issue by mweibel** [PeterDaveHello/docker-azcopy#9]
hi :wave: 

thanks for the container, much appreciated.
I wondered if you could try to [restart the failed build](https://app.travis-ci.com/github/PeterDaveHello/docker-azcopy/jobs/624756481). Not sure if there's anything else wrong but it seems to me it was just a timeout for some reason?

Thank you!

**Comment by mweibel** [comment]
on another note, it'd be great to add a license to this repo. Thanks!

**Comment by SputnikTea** [comment]
While running the multiplatform build I discovered that on `linux/arm64` the docker build step 5/5 gets stuck while downloading `go-logr/stdr v1.2.2`.
`go: downloading github.com/go-logr/stdr v1.2.2`
Why I don't know.

**Comment by PeterDaveHello** [comment]
There are some issues right now, but I don't have time to fix them. I recommend using the older version or checking with the upstream project if you need the new version. As for the license, I'll consider it, but since this is just simple application packaging, it might not be very important or necessary.
